name: Ruby CI

on:
  push:
    branches:
      - main  # Runs the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Runs the workflow on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # The job runs on the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checks out your code

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1    # Sets up Ruby for the job
      with:
        ruby-version: 3.0         # Using Ruby 3.0

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      run: |
        bundle exec rspec  
